CREATE DATABASE DB_TT;
USE DB_TT;

CREATE TABLE TIPOUSUARIO(
	cveTipoUsuario INT AUTO_INCREMENT PRIMARY KEY,
    tipoUsuario VARCHAR(100) NOT NULL
);

CREATE TABLE USUARIO(
	correo VARCHAR(100) NOT NULL PRIMARY KEY,
    usuario VARCHAR(100) NOT NULL UNIQUE,
    contrasena VARCHAR(100) NOT NULL,
    fotoUsuario BLOB,
    TIPOUSUARIO_cveTipoUsuario INT NOT NULL,
    habilidado BOOL DEFAULT TRUE
);

ALTER TABLE USUARIO ADD FOREIGN KEY (TIPOUSUARIO_cveTipoUsuario) REFERENCES TIPOUSUARIO(cveTipoUsuario);

CREATE TABLE DELEGACION(
	cveDelegacion VARCHAR(4) NOT NULL PRIMARY KEY,
    nombreDelegacion VARCHAR(100) NOT NULL
);

CREATE TABLE COLONIA(
	cveColonia INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    nombreColonia VARCHAR(100) NOT NULL,
    DELEGACION_cveDelegacion VARCHAR(4) NOT NULL
);

ALTER TABLE COLONIA ADD FOREIGN KEY (DELEGACION_cveDelegacion) REFERENCES DELEGACION(cveDelegacion);

CREATE TABLE TIPOSITIO(
	cveTipoSitio INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    tipoSitio VARCHAR(100) NOT NULL
);

CREATE TABLE SITIO(
	cveSitio INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    nombreSitio VARCHAR(100) NOT NULL,
    descripcion VARCHAR(400) NOT NULL,
    longitud DECIMAL(10,5) NOT NULL,
    latitud DECIMAL(10,5) NOT NULL,
    email VARCHAR(100),
    direccion VARCHAR(400) NOT NULL,
    numeroTelefonico varchar(12) NOT NULL,
    fechaRegistro DATE NOT NULL,
    TIPOSITIO_cveTipoSitio INT NOT NULL,
    COLONIA_cveColonia INT NOT NULL
);

ALTER TABLE SITIO ADD FOREIGN KEY (TIPOSITIO_cveTipoSitio) REFERENCES TIPOSITIO(cveTipoSitio);
ALTER TABLE SITIO ADD FOREIGN KEY (COLONIA_cveColonia) REFERENCES COLONIA(cveColonia);

CREATE TABLE FOTOSITIO(
	cveFotoSitio INT AUTO_INCREMENT NOT NULL,
    SITIO_cveSitio INT NOT NULL,
    fotoSitio BLOB NOT NULL,
    PRIMARY KEY (cveFotoSitio, SITIO_cveSitio)
);

ALTER TABLE FOTOSITIO ADD FOREIGN KEY (SITIO_cveSitio) REFERENCES SITIO(cveSitio);

CREATE TABLE HORARIO(
	cveHorario INT AUTO_INCREMENT NOT NULL,
    SITIO_cveSitio INT NOT NULL,
    dia VARCHAR(100) NOT NULL,
    horaInicio TIME NOT NULL,
    horaFinal TIME NOT NULL,
    PRIMARY KEY (cveHorario, SITIO_cveSitio)
);

ALTER TABLE HORARIO ADD FOREIGN KEY (SITIO_cveSitio) REFERENCES SITIO(cveSitio);

CREATE TABLE HISTORIAL(
	cveHistorial INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    fechaHistorial DATETIME NOT NULL,
    sitioFavorito BOOL DEFAULT FALSE,
    USUARIO_correo VARCHAR(100) NOT NULL,
    SITIO_cveSitio INT NOT NULL
);

ALTER TABLE HISTORIAL ADD FOREIGN KEY (USUARIO_correo) REFERENCES USUARIO(correo);
ALTER TABLE HISTORIAL ADD FOREIGN KEY (SITIO_cveSitio) REFERENCES SITIO(cveSitio);

CREATE TABLE SERVICIO(
	cveServicio INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    nombreServicio VARCHAR(100) NOT NULL
);

CREATE TABLE ETIQUETA(
	cveEtiqueta INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    nombreEtiqueta VARCHAR(100) NOT NULL
);

CREATE TABLE SERVICIOHOTEL(
	SITIO_cveSitio INT NOT NULL,
	SERVICIO_cveServicio INT NOT NULL,
    PRIMARY KEY(SITIO_cveSitio, SERVICIO_cveServicio)
);

ALTER TABLE SERVICIOHOTEL ADD FOREIGN KEY (SITIO_cveSitio) REFERENCES SITIO(cveSitio);
ALTER TABLE SERVICIOHOTEL ADD FOREIGN KEY (SERVICIO_cveServicio) REFERENCES SERVICIO(cveServicio);

CREATE TABLE SITIOETIQUETA(
	SITIO_cveSitio INT NOT NULL,
    ETIQUETA_cveEtiqueta INT NOT NULL,
    PRIMARY KEY(SITIO_cveSitio, ETIQUETA_cveEtiqueta)
);

ALTER TABLE SITIOETIQUETA ADD FOREIGN KEY (SITIO_cveSitio) REFERENCES SITIO(cveSitio);
ALTER TABLE SITIOETIQUETA ADD FOREIGN KEY (ETIQUETA_cveEtiqueta) REFERENCES ETIQUETA(cveEtiqueta);

CREATE TABLE COMENTARIO(
	cveComentario INT AUTO_INCREMENT,
    HISTORIAL_cveHistorial INT NOT NULL,
    comentario VARCHAR(400) NOT NULL,
    fechaComentario DATETIME NOT NULL,
    PRIMARY KEY(cveComentario, HISTORIAL_cveHistorial)
);

ALTER TABLE COMENTARIO ADD FOREIGN KEY (HISTORIAL_cveHistorial) REFERENCES HISTORIAL(cveHistorial);

CREATE TABLE FOTOCOMENTARIO(
	cveFotoComentario INT AUTO_INCREMENT,
    COMENTARIO_cveComentario INT NOT NULL,
    fotoComentario BLOB NOT NULL,
    PRIMARY KEY(cveFotoComentario, COMENTARIO_cveComentario)
);

ALTER TABLE FOTOCOMENTARIO ADD FOREIGN KEY (COMENTARIO_cveComentario) REFERENCES COMENTARIO(cveComentario);

CREATE TABLE CALIFICACION(
	cveCalificacion INT AUTO_INCREMENT PRIMARY KEY,
    calificacion DECIMAL(4,2) NOT NULL,
    HISTORIAL_cveHistorial INT NOT NULL
);

ALTER TABLE CALIFICACION ADD FOREIGN KEY (HISTORIAL_cveHistorial) REFERENCES HISTORIAL(cveHistorial);

CREATE TABLE CALIFICACIONRESTAURANTE(
	CALIFICACION_cveCalificacion INT NOT NULL PRIMARY KEY,
    atencionRestaurante INT NOT NULL,
    saborRestaurante INT NOT NULL,
    costoRestaurante INT NOT NULL,
    limpiezaRestaurante INT NOT NULL
);

ALTER TABLE CALIFICACIONRESTAURANTE ADD FOREIGN KEY (CALIFICACION_cveCalificacion) REFERENCES CALIFICACION(cveCalificacion);

CREATE TABLE CALIFICACIONHOTEL(
	CALIFICACION_cveCalificacion INT NOT NULL PRIMARY KEY,
    atencionHotel INT NOT NULL,
    limpiezaHotel INT NOT NULL,
    costoHotel INT NOT NULL
);

ALTER TABLE CALIFICACIONHOTEL ADD FOREIGN KEY (CALIFICACION_cveCalificacion) REFERENCES CALIFICACION(cveCalificacion);

CREATE TABLE PREFERENCIA(
	USUARIO_correo VARCHAR(100) NOT NULL,
    ETIQUETA_cveEtiqueta INT NOT NULL,
    primary key(USUARIO_correo, ETIQUETA_cveEtiqueta)
);

ALTER TABLE PREFERENCIA ADD FOREIGN KEY (USUARIO_correo) REFERENCES USUARIO(correo);
ALTER TABLE PREFERENCIA ADD FOREIGN KEY (ETIQUETA_cveEtiqueta) REFERENCES ETIQUETA(cveEtiqueta);

CREATE TABLE CLUSTERING(
	USUARIO_correo VARCHAR(100) NOT NULL,
    ETIQUETA_cveEtiqueta INT NOT NULL,
    primary key(USUARIO_correo, ETIQUETA_cveEtiqueta)
);

ALTER TABLE CLUSTERING ADD FOREIGN KEY (USUARIO_correo) REFERENCES USUARIO(correo);
ALTER TABLE CLUSTERING ADD FOREIGN KEY (ETIQUETA_cveEtiqueta) REFERENCES ETIQUETA(cveEtiqueta);