"""mensaje de la migración

Revision ID: 0ef8e3c1fd95
Revises: 
Create Date: 2023-06-07 22:40:31.265743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef8e3c1fd95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegacion',
    sa.Column('cve_delegacion', sa.Integer(), nullable=False),
    sa.Column('nombre_delegacion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cve_delegacion')
    )
    op.create_table('etiqueta',
    sa.Column('cve_etiqueta', sa.Integer(), nullable=False),
    sa.Column('nombre_etiqueta', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cve_etiqueta'),
    sa.UniqueConstraint('nombre_etiqueta')
    )
    op.create_table('servicio',
    sa.Column('cve_servicio', sa.Integer(), nullable=False),
    sa.Column('nombre_servicio', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cve_servicio'),
    sa.UniqueConstraint('nombre_servicio')
    )
    op.create_table('tipo_sitio',
    sa.Column('cve_tipo_sitio', sa.Integer(), nullable=False),
    sa.Column('tipo_sitio', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cve_tipo_sitio')
    )
    op.create_table('tipo_usuario',
    sa.Column('cve_tipo_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('cve_tipo_usuario')
    )
    op.create_table('colonia',
    sa.Column('cve_colonia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_colonia', sa.String(length=200), nullable=False),
    sa.Column('cve_delegacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_delegacion'], ['delegacion.cve_delegacion'], ),
    sa.PrimaryKeyConstraint('cve_colonia')
    )
    op.create_table('usuario',
    sa.Column('correo_usuario', sa.String(length=100), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=128), nullable=True),
    sa.Column('link_imagen', sa.String(length=200), nullable=True),
    sa.Column('cve_tipo_usuario', sa.Integer(), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cve_tipo_usuario'], ['tipo_usuario.cve_tipo_usuario'], ),
    sa.PrimaryKeyConstraint('correo_usuario'),
    sa.UniqueConstraint('correo_usuario'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('sitio',
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.Column('nombre_sitio', sa.String(length=400), nullable=False),
    sa.Column('longitud', sa.Float(precision=10), nullable=False),
    sa.Column('latitud', sa.Float(precision=10), nullable=False),
    sa.Column('cve_tipo_sitio', sa.Integer(), nullable=False),
    sa.Column('cve_colonia', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=800), nullable=True),
    sa.Column('correo_sitio', sa.String(length=100), nullable=True),
    sa.Column('costo_promedio', sa.Float(precision=5), nullable=True),
    sa.Column('pagina_web', sa.String(length=400), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('adscripcion', sa.String(length=400), nullable=True),
    sa.Column('calificacion', sa.Float(precision=5), nullable=True),
    sa.Column('num_calificaciones', sa.Integer(), nullable=True),
    sa.Column('habilitado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cve_colonia'], ['colonia.cve_colonia'], ),
    sa.ForeignKeyConstraint(['cve_tipo_sitio'], ['tipo_sitio.cve_tipo_sitio'], ),
    sa.PrimaryKeyConstraint('cve_sitio'),
    sa.UniqueConstraint('nombre_sitio')
    )
    op.create_table('etiqueta_restaurante',
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.Column('cve_etiqueta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_etiqueta'], ['etiqueta.cve_etiqueta'], ),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], ),
    sa.PrimaryKeyConstraint('cve_sitio', 'cve_etiqueta')
    )
    op.create_table('foto_sitio',
    sa.Column('cve_foto_sitio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_imagen', sa.String(length=400), nullable=False),
    sa.Column('nombre_imagen', sa.String(length=400), nullable=True),
    sa.Column('nombre_autor', sa.String(length=400), nullable=True),
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], ),
    sa.PrimaryKeyConstraint('cve_foto_sitio')
    )
    op.create_table('historial',
    sa.Column('cve_historial', sa.Integer(), nullable=False),
    sa.Column('me_gusta', sa.Boolean(), nullable=True),
    sa.Column('fecha_visita', sa.DateTime(), nullable=False),
    sa.Column('correo_usuario', sa.String(length=100), nullable=False),
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['correo_usuario'], ['usuario.correo_usuario'], ),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], ),
    sa.PrimaryKeyConstraint('cve_historial')
    )
    op.create_table('horario',
    sa.Column('cve_horario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dia', sa.String(length=100), nullable=False),
    sa.Column('horario_apertura', sa.Time(), nullable=False),
    sa.Column('horario_cierre', sa.Time(), nullable=False),
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], ),
    sa.PrimaryKeyConstraint('cve_horario')
    )
    op.create_table('servicio_hotel',
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.Column('cve_servicio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_servicio'], ['servicio.cve_servicio'], ),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], ),
    sa.PrimaryKeyConstraint('cve_sitio', 'cve_servicio')
    )
    op.create_table('comentario',
    sa.Column('cve_comentario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comentario', sa.String(length=400), nullable=False),
    sa.Column('fecha_comentario', sa.DateTime(), nullable=False),
    sa.Column('cve_historial', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_historial'], ['historial.cve_historial'], ),
    sa.PrimaryKeyConstraint('cve_comentario')
    )
    op.create_table('foto_comentario',
    sa.Column('cve_foto_comentario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_imagen', sa.String(length=200), nullable=False),
    sa.Column('nombre_imagen', sa.String(length=100), nullable=True),
    sa.Column('nombre_autor', sa.String(length=300), nullable=True),
    sa.Column('cve_comentario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_comentario'], ['comentario.cve_comentario'], ),
    sa.PrimaryKeyConstraint('cve_foto_comentario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foto_comentario')
    op.drop_table('comentario')
    op.drop_table('servicio_hotel')
    op.drop_table('horario')
    op.drop_table('historial')
    op.drop_table('foto_sitio')
    op.drop_table('etiqueta_restaurante')
    op.drop_table('sitio')
    op.drop_table('usuario')
    op.drop_table('colonia')
    op.drop_table('tipo_usuario')
    op.drop_table('tipo_sitio')
    op.drop_table('servicio')
    op.drop_table('etiqueta')
    op.drop_table('delegacion')
    # ### end Alembic commands ###
