"""mensaje de la migración

Revision ID: 19dc9f17df28
Revises: 0ef8e3c1fd95
Create Date: 2023-06-08 02:05:50.933016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19dc9f17df28'
down_revision = '0ef8e3c1fd95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitio_etiqueta',
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.Column('cve_etiqueta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_etiqueta'], ['etiqueta.cve_etiqueta'], ),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], ),
    sa.PrimaryKeyConstraint('cve_sitio', 'cve_etiqueta')
    )
    op.drop_table('etiqueta_restaurante')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etiqueta_restaurante',
    sa.Column('cve_sitio', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cve_etiqueta', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cve_etiqueta'], ['etiqueta.cve_etiqueta'], name='etiqueta_restaurante_ibfk_1'),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], name='etiqueta_restaurante_ibfk_2'),
    sa.PrimaryKeyConstraint('cve_sitio', 'cve_etiqueta'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('sitio_etiqueta')
    # ### end Alembic commands ###
