"""Mensaje descriptivo sobre la migración

Revision ID: 2f68ec6f0e0e
Revises: c31c2217c22d
Create Date: 2023-05-01 22:56:30.572606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f68ec6f0e0e'
down_revision = 'c31c2217c22d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sitio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('fecha_fundacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pagina_web', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('adscripcion', sa.String(length=400), nullable=True))
        batch_op.alter_column('nombre_sitio',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=400),
               existing_nullable=False)
        batch_op.alter_column('descripcion',
               existing_type=mysql.VARCHAR(length=400),
               nullable=True)
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sitio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', mysql.DATETIME(), nullable=False))
        batch_op.alter_column('descripcion',
               existing_type=mysql.VARCHAR(length=400),
               nullable=False)
        batch_op.alter_column('nombre_sitio',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('adscripcion')
        batch_op.drop_column('telefono')
        batch_op.drop_column('pagina_web')
        batch_op.drop_column('fecha_fundacion')
        batch_op.drop_column('fecha_actualizacion')

    # ### end Alembic commands ###
