"""Cambios de base de datos

Revision ID: 307b60f74e41
Revises: 5d708fb70521
Create Date: 2023-06-04 17:29:45.970239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '307b60f74e41'
down_revision = '5d708fb70521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horario', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['dia'])
        batch_op.drop_column('cve_horario')

    with op.batch_alter_table('sitio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calificacion', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('num_calificaciones', sa.Integer(), nullable=True))
        batch_op.drop_column('direccion')
        batch_op.drop_column('fecha_fundacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sitio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_fundacion', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('direccion', mysql.VARCHAR(length=400), nullable=False))
        batch_op.drop_column('num_calificaciones')
        batch_op.drop_column('calificacion')

    with op.batch_alter_table('horario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cve_horario', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
