"""mensaje de la migración

Revision ID: 5d708fb70521
Revises: c7767e9bf5ba
Create Date: 2023-05-31 10:09:06.915579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d708fb70521'
down_revision = 'c7767e9bf5ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_sitio__etiqueta',
    sa.Column('cve_tipo_sitio', sa.Integer(), nullable=False),
    sa.Column('cve_etiqueta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_etiqueta'], ['etiqueta.cve_etiqueta'], ),
    sa.ForeignKeyConstraint(['cve_tipo_sitio'], ['tipo_sitio.cve_tipo_sitio'], ),
    sa.PrimaryKeyConstraint('cve_tipo_sitio', 'cve_etiqueta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipo_sitio__etiqueta')
    # ### end Alembic commands ###
