"""mensaje de la migración

Revision ID: 64aa29b8b06a
Revises: b42d85f31620
Create Date: 2023-06-10 15:37:36.838482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64aa29b8b06a'
down_revision = 'b42d85f31620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sitio_favorito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('me_gusta', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sitio_favorito', schema=None) as batch_op:
        batch_op.drop_column('me_gusta')

    # ### end Alembic commands ###
