"""mensaje de la migración

Revision ID: 6818b350d79d
Revises: 
Create Date: 2023-06-10 15:24:06.466153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6818b350d79d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitado', sa.Boolean(), nullable=True))
        batch_op.drop_column('me_gusta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('me_gusta', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('visitado')

    # ### end Alembic commands ###
