"""mensaje de la migración

Revision ID: 6ad7831d1da1
Revises: 
Create Date: 2023-06-24 17:50:41.494714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad7831d1da1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_sitio_etiqueta',
    sa.Column('cve_tipo_sitio', sa.Integer(), nullable=False),
    sa.Column('cve_etiqueta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_etiqueta'], ['etiqueta.cve_etiqueta'], ),
    sa.ForeignKeyConstraint(['cve_tipo_sitio'], ['tipo_sitio.cve_tipo_sitio'], ),
    sa.PrimaryKeyConstraint('cve_tipo_sitio', 'cve_etiqueta')
    )
    op.create_table('usuario_servicio',
    sa.Column('correo_usuario', sa.String(length=400), nullable=False),
    sa.Column('cve_servicio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['correo_usuario'], ['usuario.correo_usuario'], ),
    sa.ForeignKeyConstraint(['cve_servicio'], ['servicio.cve_servicio'], ),
    sa.PrimaryKeyConstraint('correo_usuario', 'cve_servicio')
    )
    with op.batch_alter_table('sitio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=400), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sitio', schema=None) as batch_op:
        batch_op.drop_column('direccion')

    op.drop_table('usuario_servicio')
    op.drop_table('tipo_sitio_etiqueta')
    # ### end Alembic commands ###
