"""mensaje de la migración

Revision ID: 7cda07271e79
Revises: 96225df76419
Create Date: 2023-05-24 18:07:22.297292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cda07271e79'
down_revision = '96225df76419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_imagen', sa.String(length=400), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_comentario', schema=None) as batch_op:
        batch_op.drop_column('link_imagen')

    # ### end Alembic commands ###
