"""mensaje de la migración

Revision ID: 7fc7683660f5
Revises: 7cda07271e79
Create Date: 2023-05-24 21:14:29.379288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fc7683660f5'
down_revision = '7cda07271e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_autor', sa.String(length=400), nullable=False))

    with op.batch_alter_table('foto_sitio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_imagen', sa.String(length=400), nullable=False))
        batch_op.add_column(sa.Column('nombre_autor', sa.String(length=400), nullable=False))
        batch_op.alter_column('nombre_imagen',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=400),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_sitio', schema=None) as batch_op:
        batch_op.alter_column('nombre_imagen',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.drop_column('nombre_autor')
        batch_op.drop_column('link_imagen')

    with op.batch_alter_table('foto_comentario', schema=None) as batch_op:
        batch_op.drop_column('nombre_autor')

    # ### end Alembic commands ###
