"""mensaje de la migración

Revision ID: 85bd6418d709
Revises: 
Create Date: 2023-05-09 21:02:49.530902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85bd6418d709'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_sitio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruta_sitio', sa.String(length=500), nullable=False))
        batch_op.drop_column('foto_sitio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_sitio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_sitio', mysql.VARCHAR(length=400), nullable=False))
        batch_op.drop_column('ruta_sitio')

    # ### end Alembic commands ###
