"""mensaje de la migración

Revision ID: 8ddff19cd443
Revises: bbd51f5c06bd
Create Date: 2023-05-22 14:59:46.877107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ddff19cd443'
down_revision = 'bbd51f5c06bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_imagen', sa.String(length=400), nullable=True))
        batch_op.drop_column('ruta_foto_usuario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruta_foto_usuario', mysql.VARCHAR(length=400), nullable=True))
        batch_op.drop_column('nombre_imagen')

    # ### end Alembic commands ###
