"""mensaje de la migración

Revision ID: 96225df76419
Revises: c863f6ee88cc
Create Date: 2023-05-22 21:46:44.462542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96225df76419'
down_revision = 'c863f6ee88cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sitio', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=mysql.VARCHAR(length=400),
               type_=sa.String(length=800),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sitio', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=800),
               type_=mysql.VARCHAR(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###
