"""mensaje de la migración

Revision ID: 9bbdd974017b
Revises: 307b60f74e41
Create Date: 2023-06-04 18:54:30.645146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbdd974017b'
down_revision = '307b60f74e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cve_horario', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_index('dia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horario', schema=None) as batch_op:
        batch_op.create_index('dia', ['dia'], unique=False)
        batch_op.drop_column('cve_horario')

    # ### end Alembic commands ###
