"""mensaje de la migración

Revision ID: b42d85f31620
Revises: 6818b350d79d
Create Date: 2023-06-10 15:27:07.615279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42d85f31620'
down_revision = '6818b350d79d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitio_favorito',
    sa.Column('correo_usuario', sa.String(length=100), nullable=False),
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['correo_usuario'], ['usuario.correo_usuario'], ),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], ),
    sa.PrimaryKeyConstraint('correo_usuario', 'cve_sitio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sitio_favorito')
    # ### end Alembic commands ###
