"""empty message

Revision ID: c31c2217c22d
Revises: 
Create Date: 2023-04-25 08:09:02.032128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31c2217c22d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegacion',
    sa.Column('cve_delegacion', sa.Integer(), nullable=False),
    sa.Column('nombre_delegacion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cve_delegacion')
    )
    op.create_table('etiqueta',
    sa.Column('cve_etiqueta', sa.Integer(), nullable=False),
    sa.Column('nombre_etiqueta', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cve_etiqueta')
    )
    op.create_table('servicio',
    sa.Column('cve_servicio', sa.Integer(), nullable=False),
    sa.Column('nombre_servicio', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cve_servicio')
    )
    op.create_table('tipo_sitio',
    sa.Column('cve_tipo_sitio', sa.Integer(), nullable=False),
    sa.Column('tipo_sitio', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cve_tipo_sitio')
    )
    op.create_table('tipo_usuario',
    sa.Column('cve_tipo_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('cve_tipo_usuario')
    )
    op.create_table('colonia',
    sa.Column('cve_colonia', sa.Integer(), nullable=False),
    sa.Column('nombre_colonia', sa.String(length=400), nullable=False),
    sa.Column('cve_delegacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_delegacion'], ['delegacion.cve_delegacion'], ),
    sa.PrimaryKeyConstraint('cve_colonia')
    )
    op.create_table('etiqueta_tipo_sitio',
    sa.Column('cve_tipo_sitio', sa.Integer(), nullable=False),
    sa.Column('cve_etiqueta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_etiqueta'], ['etiqueta.cve_etiqueta'], ),
    sa.ForeignKeyConstraint(['cve_tipo_sitio'], ['tipo_sitio.cve_tipo_sitio'], ),
    sa.PrimaryKeyConstraint('cve_tipo_sitio', 'cve_etiqueta')
    )
    op.create_table('usuario',
    sa.Column('correo_usuario', sa.String(length=100), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=100), nullable=False),
    sa.Column('foto_usuario', sa.LargeBinary(), nullable=True),
    sa.Column('cve_tipo_usuario', sa.Integer(), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cve_tipo_usuario'], ['tipo_usuario.cve_tipo_usuario'], ),
    sa.PrimaryKeyConstraint('correo_usuario')
    )
    op.create_table('preferencia',
    sa.Column('correo_usuario', sa.String(length=100), nullable=False),
    sa.Column('cve_etiqueta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['correo_usuario'], ['usuario.correo_usuario'], ),
    sa.ForeignKeyConstraint(['cve_etiqueta'], ['etiqueta.cve_etiqueta'], ),
    sa.PrimaryKeyConstraint('correo_usuario', 'cve_etiqueta')
    )
    op.create_table('sitio',
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.Column('nombre_sitio', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=400), nullable=False),
    sa.Column('x_longitud', sa.Float(precision=10), nullable=False),
    sa.Column('y_latitud', sa.Float(precision=10), nullable=False),
    sa.Column('correo_sitio', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=400), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('costo_promedio', sa.Float(precision=2), nullable=True),
    sa.Column('habilitado', sa.Boolean(), nullable=True),
    sa.Column('cve_tipo_sitio', sa.Integer(), nullable=False),
    sa.Column('cve_colonia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_colonia'], ['colonia.cve_colonia'], ),
    sa.ForeignKeyConstraint(['cve_tipo_sitio'], ['tipo_sitio.cve_tipo_sitio'], ),
    sa.PrimaryKeyConstraint('cve_sitio')
    )
    op.create_table('foto_sitio',
    sa.Column('cve_foto_sitio', sa.Integer(), nullable=False),
    sa.Column('foto_sitio', sa.String(length=400), nullable=False),
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], ),
    sa.PrimaryKeyConstraint('cve_foto_sitio')
    )
    op.create_table('historial',
    sa.Column('cve_historial', sa.Integer(), nullable=False),
    sa.Column('favorito', sa.Boolean(), nullable=True),
    sa.Column('ultima_visita', sa.DateTime(), nullable=False),
    sa.Column('cve_usuario', sa.String(length=100), nullable=False),
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], ),
    sa.ForeignKeyConstraint(['cve_usuario'], ['usuario.correo_usuario'], ),
    sa.PrimaryKeyConstraint('cve_historial')
    )
    op.create_table('horario',
    sa.Column('cve_horario', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(length=100), nullable=False),
    sa.Column('horario_apertura', sa.Time(), nullable=False),
    sa.Column('horario_cierre', sa.Time(), nullable=False),
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], ),
    sa.PrimaryKeyConstraint('cve_horario')
    )
    op.create_table('servicio_hotel',
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.Column('cve_servicio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_servicio'], ['servicio.cve_servicio'], ),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], ),
    sa.PrimaryKeyConstraint('cve_sitio', 'cve_servicio')
    )
    op.create_table('sitio_etiqueta',
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.Column('cve_etiqueta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_etiqueta'], ['etiqueta.cve_etiqueta'], ),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], ),
    sa.PrimaryKeyConstraint('cve_sitio', 'cve_etiqueta')
    )
    op.create_table('calificacion',
    sa.Column('cve_calificacion', sa.Integer(), nullable=False),
    sa.Column('cve_historial', sa.Integer(), nullable=False),
    sa.Column('calificacion_general', sa.Float(precision=2), nullable=False),
    sa.Column('calificaciones_especificas', sa.JSON(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cve_historial'], ['historial.cve_historial'], ),
    sa.PrimaryKeyConstraint('cve_calificacion')
    )
    op.create_table('comentario',
    sa.Column('cve_comentario', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=400), nullable=False),
    sa.Column('fecha_comentario', sa.DateTime(), nullable=False),
    sa.Column('cve_historial', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_historial'], ['historial.cve_historial'], ),
    sa.PrimaryKeyConstraint('cve_comentario')
    )
    op.create_table('foto_comentario',
    sa.Column('cve_foto_comentario', sa.Integer(), nullable=False),
    sa.Column('foto_comentario', sa.String(length=400), nullable=False),
    sa.Column('cve_comentario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_comentario'], ['comentario.cve_comentario'], ),
    sa.PrimaryKeyConstraint('cve_foto_comentario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foto_comentario')
    op.drop_table('comentario')
    op.drop_table('calificacion')
    op.drop_table('sitio_etiqueta')
    op.drop_table('servicio_hotel')
    op.drop_table('horario')
    op.drop_table('historial')
    op.drop_table('foto_sitio')
    op.drop_table('sitio')
    op.drop_table('preferencia')
    op.drop_table('usuario')
    op.drop_table('etiqueta_tipo_sitio')
    op.drop_table('colonia')
    op.drop_table('tipo_usuario')
    op.drop_table('tipo_sitio')
    op.drop_table('servicio')
    op.drop_table('etiqueta')
    op.drop_table('delegacion')
    # ### end Alembic commands ###
