"""mensaje de la migración

Revision ID: c7767e9bf5ba
Revises: 7fc7683660f5
Create Date: 2023-05-30 18:06:04.528594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7767e9bf5ba'
down_revision = '7fc7683660f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_sitio', schema=None) as batch_op:
        batch_op.alter_column('link_imagen',
               existing_type=mysql.VARCHAR(length=400),
               nullable=True)
        batch_op.alter_column('nombre_autor',
               existing_type=mysql.VARCHAR(length=400),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_sitio', schema=None) as batch_op:
        batch_op.alter_column('nombre_autor',
               existing_type=mysql.VARCHAR(length=400),
               nullable=False)
        batch_op.alter_column('link_imagen',
               existing_type=mysql.VARCHAR(length=400),
               nullable=False)

    # ### end Alembic commands ###
