"""mensaje de la migración

Revision ID: c863f6ee88cc
Revises: 8ddff19cd443
Create Date: 2023-05-22 18:06:44.768996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c863f6ee88cc'
down_revision = '8ddff19cd443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_imagen', sa.String(length=400), nullable=False))
        batch_op.drop_column('ruta_foto_comentario')

    with op.batch_alter_table('foto_sitio', schema=None) as batch_op:
        batch_op.drop_column('ruta_sitio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_sitio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruta_sitio', mysql.VARCHAR(length=500), nullable=False))

    with op.batch_alter_table('foto_comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruta_foto_comentario', mysql.VARCHAR(length=400), nullable=False))
        batch_op.drop_column('nombre_imagen')

    # ### end Alembic commands ###
