"""Se agrega imagen a modelo tipo sitio

Revision ID: dcd0ed17557a
Revises: d30b7584ea32
Create Date: 2023-05-14 20:40:20.958618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dcd0ed17557a'
down_revision = 'd30b7584ea32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitas_sitio',
    sa.Column('cve_visita', sa.Integer(), nullable=False),
    sa.Column('fecha_visita', sa.DateTime(), nullable=False),
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], ),
    sa.PrimaryKeyConstraint('cve_visita')
    )
    op.create_table('calificacion_hotel',
    sa.Column('cve_calificacion', sa.Integer(), nullable=False),
    sa.Column('calidad_servicio', sa.Float(), nullable=False),
    sa.Column('costo', sa.Float(), nullable=False),
    sa.Column('limpieza', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cve_calificacion'], ['calificacion.cve_calificacion'], ),
    sa.PrimaryKeyConstraint('cve_calificacion')
    )
    op.create_table('calificacion_restaurante',
    sa.Column('cve_calificacion', sa.Integer(), nullable=False),
    sa.Column('calidad_servicio', sa.Float(), nullable=False),
    sa.Column('sabor', sa.Float(), nullable=False),
    sa.Column('costo', sa.Float(), nullable=False),
    sa.Column('limpieza', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cve_calificacion'], ['calificacion.cve_calificacion'], ),
    sa.PrimaryKeyConstraint('cve_calificacion')
    )
    with op.batch_alter_table('calificacion', schema=None) as batch_op:
        batch_op.drop_column('tipo')
        batch_op.drop_column('calificaciones_especificas')

    with op.batch_alter_table('etiqueta', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre_etiqueta'])

    with op.batch_alter_table('historial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('me_gusta', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fecha_visita', sa.DateTime(), nullable=False))
        batch_op.drop_column('favorito')
        batch_op.drop_column('ultima_visita')

    with op.batch_alter_table('tipo_sitio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruta_imagen', sa.String(length=400), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_sitio', schema=None) as batch_op:
        batch_op.drop_column('ruta_imagen')

    with op.batch_alter_table('historial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_visita', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('favorito', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('fecha_visita')
        batch_op.drop_column('me_gusta')

    with op.batch_alter_table('etiqueta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('calificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calificaciones_especificas', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tipo', mysql.VARCHAR(length=50), nullable=True))

    op.drop_table('calificacion_restaurante')
    op.drop_table('calificacion_hotel')
    op.drop_table('visitas_sitio')
    # ### end Alembic commands ###
