"""mensaje de la migración

Revision ID: e3c018ccb8cc
Revises: 9bbdd974017b
Create Date: 2023-06-05 15:00:50.951659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3c018ccb8cc'
down_revision = '9bbdd974017b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_imagen', sa.String(length=400), nullable=True))
        batch_op.drop_column('nombre_imagen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_imagen', mysql.VARCHAR(length=400), nullable=True))
        batch_op.drop_column('link_imagen')

    # ### end Alembic commands ###
