"""mensaje de la migración

Revision ID: ead6052b16a0
Revises: f0a2598b1976
Create Date: 2023-05-17 07:13:21.426099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ead6052b16a0'
down_revision = 'f0a2598b1976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_sitio', schema=None) as batch_op:
        batch_op.alter_column('ruta_imagen',
               existing_type=mysql.VARCHAR(length=400),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_sitio', schema=None) as batch_op:
        batch_op.alter_column('ruta_imagen',
               existing_type=mysql.VARCHAR(length=400),
               nullable=False)

    # ### end Alembic commands ###
