"""Initial migration

Revision ID: f0a2598b1976
Revises: 
Create Date: 2023-05-17 06:37:40.989103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a2598b1976'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegacion',
    sa.Column('cve_delegacion', sa.Integer(), nullable=False),
    sa.Column('nombre_delegacion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cve_delegacion')
    )
    op.create_table('etiqueta',
    sa.Column('cve_etiqueta', sa.Integer(), nullable=False),
    sa.Column('nombre_etiqueta', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cve_etiqueta'),
    sa.UniqueConstraint('nombre_etiqueta')
    )
    op.create_table('servicio',
    sa.Column('cve_servicio', sa.Integer(), nullable=False),
    sa.Column('nombre_servicio', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cve_servicio')
    )
    op.create_table('tipo_sitio',
    sa.Column('cve_tipo_sitio', sa.Integer(), nullable=False),
    sa.Column('tipo_sitio', sa.String(length=100), nullable=False),
    sa.Column('ruta_imagen', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('cve_tipo_sitio')
    )
    op.create_table('tipo_usuario',
    sa.Column('cve_tipo_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('cve_tipo_usuario')
    )
    op.create_table('colonia',
    sa.Column('cve_colonia', sa.Integer(), nullable=False),
    sa.Column('nombre_colonia', sa.String(length=400), nullable=False),
    sa.Column('cve_delegacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_delegacion'], ['delegacion.cve_delegacion'], ),
    sa.PrimaryKeyConstraint('cve_colonia')
    )
    op.create_table('etiqueta_tipo_sitio',
    sa.Column('cve_tipo_sitio', sa.Integer(), nullable=False),
    sa.Column('cve_etiqueta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_etiqueta'], ['etiqueta.cve_etiqueta'], ),
    sa.ForeignKeyConstraint(['cve_tipo_sitio'], ['tipo_sitio.cve_tipo_sitio'], ),
    sa.PrimaryKeyConstraint('cve_tipo_sitio', 'cve_etiqueta')
    )
    op.create_table('usuario',
    sa.Column('correo_usuario', sa.String(length=100), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=128), nullable=True),
    sa.Column('ruta_foto_usuario', sa.String(length=400), nullable=True),
    sa.Column('cve_tipo_usuario', sa.Integer(), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cve_tipo_usuario'], ['tipo_usuario.cve_tipo_usuario'], ),
    sa.PrimaryKeyConstraint('correo_usuario'),
    sa.UniqueConstraint('correo_usuario'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('preferencia',
    sa.Column('correo_usuario', sa.String(length=100), nullable=False),
    sa.Column('cve_etiqueta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['correo_usuario'], ['usuario.correo_usuario'], ),
    sa.ForeignKeyConstraint(['cve_etiqueta'], ['etiqueta.cve_etiqueta'], ),
    sa.PrimaryKeyConstraint('correo_usuario', 'cve_etiqueta')
    )
    op.create_table('sitio',
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.Column('nombre_sitio', sa.String(length=400), nullable=False),
    sa.Column('x_longitud', sa.Float(precision=10), nullable=False),
    sa.Column('y_latitud', sa.Float(precision=10), nullable=False),
    sa.Column('direccion', sa.String(length=400), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.Column('descripcion', sa.String(length=400), nullable=True),
    sa.Column('correo_sitio', sa.String(length=100), nullable=True),
    sa.Column('fecha_fundacion', sa.DateTime(), nullable=True),
    sa.Column('costo_promedio', sa.Float(precision=5), nullable=True),
    sa.Column('habilitado', sa.Boolean(), nullable=True),
    sa.Column('pagina_web', sa.String(length=400), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('adscripcion', sa.String(length=400), nullable=True),
    sa.Column('cve_tipo_sitio', sa.Integer(), nullable=False),
    sa.Column('cve_colonia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_colonia'], ['colonia.cve_colonia'], ),
    sa.ForeignKeyConstraint(['cve_tipo_sitio'], ['tipo_sitio.cve_tipo_sitio'], ),
    sa.PrimaryKeyConstraint('cve_sitio'),
    sa.UniqueConstraint('nombre_sitio')
    )
    op.create_table('foto_sitio',
    sa.Column('cve_foto_sitio', sa.Integer(), nullable=False),
    sa.Column('ruta_sitio', sa.String(length=500), nullable=False),
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], ),
    sa.PrimaryKeyConstraint('cve_foto_sitio')
    )
    op.create_table('historial',
    sa.Column('cve_historial', sa.Integer(), nullable=False),
    sa.Column('me_gusta', sa.Boolean(), nullable=True),
    sa.Column('fecha_visita', sa.DateTime(), nullable=False),
    sa.Column('cve_usuario', sa.String(length=100), nullable=False),
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], ),
    sa.ForeignKeyConstraint(['cve_usuario'], ['usuario.correo_usuario'], ),
    sa.PrimaryKeyConstraint('cve_historial')
    )
    op.create_table('horario',
    sa.Column('cve_horario', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(length=100), nullable=False),
    sa.Column('horario_apertura', sa.Time(), nullable=False),
    sa.Column('horario_cierre', sa.Time(), nullable=False),
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], ),
    sa.PrimaryKeyConstraint('cve_horario')
    )
    op.create_table('servicio_hotel',
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.Column('cve_servicio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_servicio'], ['servicio.cve_servicio'], ),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], ),
    sa.PrimaryKeyConstraint('cve_sitio', 'cve_servicio')
    )
    op.create_table('sitio_etiqueta',
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.Column('cve_etiqueta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_etiqueta'], ['etiqueta.cve_etiqueta'], ),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], ),
    sa.PrimaryKeyConstraint('cve_sitio', 'cve_etiqueta')
    )
    op.create_table('visitas_sitio',
    sa.Column('cve_visita', sa.Integer(), nullable=False),
    sa.Column('fecha_visita', sa.DateTime(), nullable=False),
    sa.Column('cve_sitio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_sitio'], ['sitio.cve_sitio'], ),
    sa.PrimaryKeyConstraint('cve_visita')
    )
    op.create_table('calificacion',
    sa.Column('cve_calificacion', sa.Integer(), nullable=False),
    sa.Column('calificacion_general', sa.Float(), nullable=False),
    sa.Column('cve_historial', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_historial'], ['historial.cve_historial'], ),
    sa.PrimaryKeyConstraint('cve_calificacion')
    )
    op.create_table('comentario',
    sa.Column('cve_comentario', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=400), nullable=False),
    sa.Column('fecha_comentario', sa.DateTime(), nullable=False),
    sa.Column('cve_historial', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_historial'], ['historial.cve_historial'], ),
    sa.PrimaryKeyConstraint('cve_comentario')
    )
    op.create_table('calificacion_hotel',
    sa.Column('cve_calificacion', sa.Integer(), nullable=False),
    sa.Column('calidad_servicio', sa.Float(), nullable=False),
    sa.Column('costo', sa.Float(), nullable=False),
    sa.Column('limpieza', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cve_calificacion'], ['calificacion.cve_calificacion'], ),
    sa.PrimaryKeyConstraint('cve_calificacion')
    )
    op.create_table('calificacion_restaurante',
    sa.Column('cve_calificacion', sa.Integer(), nullable=False),
    sa.Column('calidad_servicio', sa.Float(), nullable=False),
    sa.Column('sabor', sa.Float(), nullable=False),
    sa.Column('costo', sa.Float(), nullable=False),
    sa.Column('limpieza', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cve_calificacion'], ['calificacion.cve_calificacion'], ),
    sa.PrimaryKeyConstraint('cve_calificacion')
    )
    op.create_table('foto_comentario',
    sa.Column('cve_foto_comentario', sa.Integer(), nullable=False),
    sa.Column('ruta_foto_comentario', sa.String(length=400), nullable=False),
    sa.Column('cve_comentario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_comentario'], ['comentario.cve_comentario'], ),
    sa.PrimaryKeyConstraint('cve_foto_comentario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foto_comentario')
    op.drop_table('calificacion_restaurante')
    op.drop_table('calificacion_hotel')
    op.drop_table('comentario')
    op.drop_table('calificacion')
    op.drop_table('visitas_sitio')
    op.drop_table('sitio_etiqueta')
    op.drop_table('servicio_hotel')
    op.drop_table('horario')
    op.drop_table('historial')
    op.drop_table('foto_sitio')
    op.drop_table('sitio')
    op.drop_table('preferencia')
    op.drop_table('usuario')
    op.drop_table('etiqueta_tipo_sitio')
    op.drop_table('colonia')
    op.drop_table('tipo_usuario')
    op.drop_table('tipo_sitio')
    op.drop_table('servicio')
    op.drop_table('etiqueta')
    op.drop_table('delegacion')
    # ### end Alembic commands ###
