from .calificacion_hotel import CalificacionHotel
from .calificacion_restaurante import CalificacionRestaurante
from .calificacion import Calificacion
from .colonia import Colonia
from .comentario import Comentario
from .delegacion import Delegacion
# from .etiqueta_tipo_sitio import EtiquetaTipoSitio
from .etiqueta import Etiqueta
from .foto_comentario import FotoComentario
from .foto_sitio import FotoSitio
from .historial import Historial
from .horario import Horario
from .preferencia import Preferencia
from .servicio_hotel import ServicioHotel
from .servicio import Servicio
from .sitio_etiqueta import SitioEtiqueta
from .sitio import Sitio
from .tipo_sitio import TipoSitio
from .tipo_usuario import TipoUsuario
from .usuario import Usuario
from .visitas_sitio import VisitasSitio
